export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INCREMENT_ODD = "INCREMENT_ODD";
export const DECREMENT_EVEN = "DECREMENT_EVEN";
export const INCREMENT_ASYNC = "INCREMENT_ASYNC";
